export interface BrandMigrationEntity {
  id: number;
  name: string;
}

export const BRAND_MIGRATION_ENTITIES: BrandMigrationEntity[] = [
  { id: 1, name: "VONbLÜTE" },
  { id: 2, name: "Green House Seed Co." },
  { id: 3, name: "Hanf Im Glück" },
  { id: 9, name: "nevernot" },
  { id: 10, name: "Grove Bags" },
  { id: 14, name: "Baast" },
  { id: 16, name: "Hazefly" },
  { id: 17, name: "SMOWE" },
  { id: 18, name: "Cannafleur" },
  { id: 19, name: "Weedo" },
  { id: 20, name: "Hempcrew" },
  { id: 21, name: "Malantis" },
  { id: 22, name: "Seedstockers" },
  { id: 26, name: "GrowHub" },
  { id: 27, name: "Spliffers" },
  { id: 28, name: "Weed Brand" },
  { id: 29, name: "Focus V" },
  { id: 30, name: "Weed" },
  { id: 32, name: "G13 Labs" },
  { id: 33, name: "PAX" },
  { id: 34, name: "Alweeda" },
  { id: 35, name: "Royal Queen Seeds" },
  { id: 36, name: "Kailar" },
  { id: 37, name: "STORZ & BICKEL" },
  { id: 40, name: "NOIDS" },
  { id: 43, name: "Cannasseur Club" },
  { id: 44, name: "PartnerBrandsName" },
  { id: 46, name: "Vapes'n'Dabs" },
  { id: 47, name: "Skunky Monkey" },
  { id: 49, name: "Tyson 2.0 Deutschland" },
  { id: 50, name: "etos* - extraordinaryshit" },
  { id: 52, name: "EasyHomeGrowing" },
  { id: 53, name: "Kannavi" },
  { id: 55, name: "Dutch Passion" },
  { id: 56, name: "INHALE Vaporizers" },
  { id: 57, name: "HEMPER" },
  { id: 59, name: "Treez Tools" },
  { id: 60, name: "Treez Club" },
  { id: 61, name: "Original Kavatza" },
  { id: 62, name: "Seedstockers Plants" },
  { id: 64, name: "Four 20 Origins" },
  { id: 65, name: "Smoking" },
  { id: 66, name: "Plantalytix" },
  { id: 67, name: "MariGold" },
  { id: 70, name: "Monpti" },
  { id: 71, name: "Hempamed" },
  { id: 72, name: "Hybrid Filter" },
  { id: 73, name: "Super Puff" },
  { id: 74, name: "Super Strains" },
  { id: 76, name: "Hy-Pro" },
  { id: 77, name: "Feel Good" },
  { id: 80, name: "DOKTORTHC.COM" },
  { id: 81, name: "Happy420" },
  { id: 82, name: "Hempions" },
  { id: 83, name: "STEEZY GmbH" },
  { id: 84, name: "Green Deal" },
  { id: 85, name: "MUZA" },
  { id: 87, name: "Feel it Green" },
  { id: 88, name: "Nadel87" },
  { id: 89, name: "Mary Mellow" },
  { id: 90, name: "finom Metall" },
  { id: 92, name: "Hanf.com" },
  { id: 94, name: "Fürni" },
  { id: 95, name: "DoktorTHC" },
  { id: 96, name: "Cannoptikum" },
  { id: 98, name: "Hotyek" },
  { id: 99, name: "Die Hanf-App" },
  { id: 100, name: "Merkur Apotheke" },
  { id: 101, name: "Wuchsmeister" },
  { id: 102, name: "Home420" },
  { id: 103, name: "SWISS FX" },
  { id: 105, name: "GROW®" },
  { id: 106, name: "HAMAKA" },
  { id: 107, name: "Weeds Republic" },
  { id: 108, name: "CBDÍA" },
  { id: 109, name: "Hempli.de" },
  { id: 110, name: "CBDSÍ" },
  { id: 112, name: "Zamnesia" },
  { id: 113, name: "Sativa-sorten" },
  { id: 114, name: "Cannadoca" },
  { id: 117, name: "CANNAVIGIA" },
  { id: 118, name: "MySeeds" },
  { id: 119, name: "Medusafilters" },
  { id: 120, name: "Scale xv2" },
  { id: 121, name: "DabberSupply" },
  { id: 123, name: "Relifa" },
  { id: 124, name: "Herbaleafs" },
  { id: 125, name: "RENACT" },
  { id: 126, name: "House of Seeds" },
  { id: 127, name: "Holy Hemp" },
  { id: 128, name: "CarbonActive Products AG" },
  { id: 129, name: "OnlyGrams" },
  { id: 131, name: "High4Life" },
  { id: 132, name: "NIPRO Designs" },
  { id: 133, name: "WeedsPayments" },
  { id: 135, name: "Canna Smile" },
  { id: 136, name: "VIDA SKINCARE" },
  { id: 137, name: "Ganja Farmer" },
  { id: 138, name: "E10 Labs" },
  { id: 140, name: "The Original Cones" },
  { id: 141, name: "Vivosun" },
  { id: 142, name: "Green Rush" },
  { id: 143, name: "ENDOCA" },
  { id: 144, name: "JulieBrand" },
  { id: 145, name: "hypnoseeds" },
  { id: 146, name: "HIZEN Vaporizers" },
  { id: 147, name: "DrainMaster" },
  { id: 149, name: "Willz Bar" },
  { id: 151, name: "Dropsteckling" },
  { id: 1006, name: "LOT 420" },
  { id: 1014, name: "Ozo" },
  { id: 1015, name: "Toncz" },
  { id: 1017, name: "Green House Feeding" },
  { id: 1018, name: "Omura" },
  { id: 1019, name: "Marychainz" },
  { id: 1022, name: "Flow Inc. Growshop & Consulting" },
  { id: 1023, name: "STYCKY" },
];

export const BRAND_MIGRATION_IDS = BRAND_MIGRATION_ENTITIES.map((entity) => entity.id);

const NAME_LOOKUP = new Set(BRAND_MIGRATION_ENTITIES.map((entity) => entity.name.toLowerCase()));
export function isBrandMigrationName(name?: string | null): boolean {
  return typeof name === "string" && NAME_LOOKUP.has(name.toLowerCase());
}

const ID_LOOKUP = new Set(BRAND_MIGRATION_ENTITIES.map((entity) => entity.id));
export function isBrandMigrationId(id?: number | null): boolean {
  return typeof id === "number" && ID_LOOKUP.has(id);
}

export function shouldTreatAsBrand(identifier: { id?: number | null; name?: string | null }): boolean {
  return isBrandMigrationId(identifier.id ?? null) || isBrandMigrationName(identifier.name ?? null);
}

